Products/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from .views import *

admin.autodiscover()
app_name = 'Products'

urlpatterns = [

    url(r'^update_product_review/(?P<pk>\d+)/$', update_product_review, name='update_product_review'),
    url(r'^apply_promo/$', apply_promo, name='apply_promo'),
    # admin dashboard
    # product
    url(r'^dashboard/$', productdashboard, name='product_dashboard'),
    url(r'^add_product_dashboard/$', addproductdashboard, name='add_product_dashboard'),
    url(r'^edit_product_dashboard/(?P<pk>\d+)/$', editproductdashboard, name='edit_product_dashboard'),
    url(r'^delete_product_dashboard/(?P<pk>\d+)/$', deleteproductdashboard, name='delete_product_dashboard'),

    #category
    url(r'^category_dashboard/$', category_dashboard, name='category_dashboard'),
    url(r'^add_category_dashboard/$', addcategorydashboard, name='add_category_dashboard'),
    url(r'^edit_category_dashboard/(?P<pk>\d+)/$', editcategorydashboard, name='edit_category_dashboard'),
    url(r'^delete_category_dashboard/(?P<pk>\d+)/$', deletecategorydashboard, name='delete_category_dashboard'),

    #product type
    url(r'^product_type/$', producttypedashboard, name='product_type_dashboard'),
    url(r'^add_product_type/$', add_producttypedashboard, name='add_product_type_dashboard'),
    
    #product type
    url(r'^order_dashoard/$', order_dashoard, name='order_dashoard'),
    url(r'^order_not_delivered/$', order_not_delivered_dashboard, name='order_not_delivered_dashboard'),
    url(r'^order_delivered/$', order_delivered_dashboard, name='order_delivered_dashboard'),
    url(r'^update_order_delivery_status/(?P<pk>\d+)/$', update_order_delivery_status_dashboard, name='update_order_delivery_status_dashboard'),
]

accounts/urls.py
from .views import *
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', Logout.as_view(), name='logout'),
    url(r'^register/$', Register.as_view(), name='register'),
    url(r'^change_passord/$', change_password, name='change_password'),
    url(r'^add_new_address/$', add_new_address, name='add_new_address'),
    url(r'^delete_user_address/(?P<pk>\d+)/$', delete_user_address, name='delete_user_address'),
    # admin dashboard
    url(r'^customers/$', customers_dashboard, name='customers_dashboard'),
    url(r'^add_customers/$', add_customers_dashboard, name='add_customers_dashboard'),
    url(r'^edit_customers/(?P<pk>\d+)/$', edit_customers_dashboard, name='edit_customers_dashboard'),
    url(r'^delete_customer_dashboard/(?P<pk>\d+)/$', deletecustomerdashboard, name='delete_customers_dashboard'),
]

api/urls.py
from .views import *
from django.conf.urls import url
from django.urls import include, path



urlpatterns = [
    url(r'filter_product/$',filter_product.as_view(),name="filter_product"),
    url(r'add_user_wishlist/$',Add_user_wish_list_item.as_view(),name="Add_user_wish_list_item"),
    url(r'delete_user_wishlist/$',delete_user_wish_list_item.as_view(),name="delete_user_wish_list_item"),
    url(r'add_user_cartlist/$',Add_user_cart_list_item.as_view(),name="Add_user_cart_list_item"),
    url(r'delete_user_cartlist/$',delete_user_cart_list_item.as_view(),name="delete_user_cart_list_item"),
]

frontend/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

from .views import * 
app_name = 'frontend'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile', views.profile, name='profile'),
    url(r'^add-product-wishlist', views.add_product_wishlist, name='add_product_wishlist'),
    url(r'^updateprofile', views.updateprofile, name='updateprofile'),
    url(r'^product/(?P<pk>\d+)/$', each_products, name='each_products'),
    url(r'^products/(?P<pk>\d+)/$', products, name='products'),
    url(r'^acessories', acessories, name='acessories'),
    url(r'^filter_product', filter_product, name='filter_product'),
    url(r'^search', seach_product, name='seach_product'),
    url(r'^wishlist', userwishlist, name='userwishlist'),
    url(r'^add_wishlist_to_cart', add_wishlist_to_cart, name='add_wishlist_to_cart'),
    url(r'^cartlist', usercartlist, name='usercartlist'),
    url(r'^customeproduct', usercustomeproduct, name='usercustomeproduct'),
    url(r'^customeshirt', usercustomeshirt, name='usercustomeshirt'),
    url(r'^customedesign', usercustomedesign, name='usercustomedesign'),
    url(r'^checkout', usercheckout, name='usercheckout'),
    url(r'^order_placed', userorderplaced, name='userorderplaced'),
    url(r'^create_checkout_session', create_checkout_session, name='create_checkout_session'),
    url(r'^about', about, name='about'),
    url(r'^faq', faq, name='faq'),
    url(r'^contact_us', contact_us, name='contact_us'),
    url(r'^coming_soon', coming_soon, name='coming_soon'),
    # path('cancelled/', views.CancelledView.as_view()),
    # path('webhook/', views.stripe_webhook), # new

    # admin dashboard
    url(r'^main_carousel', main_carousel, name='main_carousel'),
    url(r'^edit_main_carousel_dashboard/(?P<pk>\d+)/$', edit_main_carousel_dashboard, name='edit_main_carousel_dashboard'),
    url(r'^edit_sale_banner_dashboard/(?P<pk>\d+)/$', edit_sale_banner_dashboard, name='edit_sale_banner_dashboard'),
    url(r'^edit_countdown_banner_dashboard/(?P<pk>\d+)/$', edit_countdown_banner_dashboard, name='edit_countdown_banner_dashboard'),
    url(r'^edit_category_banner_dashboard/(?P<pk>\d+)/$', edit_category_banner_dashboard, name='edit_category_banner_dashboard'),
    url(r'^edit_custom_shirt_banner_dashboard/(?P<pk>\d+)/$', edit_custom_shirt_banner_dashboard, name='edit_custom_shirt_banner_dashboard'),
    url(r'^view_testimonials', view_testimonials, name='view_testimonials'),
    url(r'^add_testimonials', add_testimonials, name='add_testimonials'),
    url(r'^edit_testimonials/(?P<pk>\d+)/$', edit_testimonials, name='edit_testimonials'),
    url(r'^delete_testimonials/(?P<pk>\d+)/$', delete_testimonials, name='delete_testimonials'),
    url(r'^view_faq', view_faq, name='view_faq'),
    url(r'^add_faq', add_faq, name='add_faq'),
    url(r'^edit_faq/(?P<pk>\d+)/$', edit_faq, name='edit_faq'),
    url(r'^delete_faq/(?P<pk>\d+)/$', delete_faq, name='delete_faq'),
    url(r'^contact_info', contact_info, name='contact_info'),
    url(r'^add_contact_info', add_contact_info, name='add_contact_info'),
    url(r'^edit_contact_info/(?P<pk>\d+)/$', edit_contact_info, name='edit_contact_info'),
    url(r'^delete_contact_info/(?P<pk>\d+)/$', delete_contact_info, name='delete_contact_info'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls')),
    path('accounts/',include('accounts.urls')),
    path('products/',include('Products.urls')),
    path('api/',include('api.urls')),
    path("google/", include("allauth.urls"), name='google_login'),
    # path('auth/google/', GoogleLogin.as_view(), name='google_login'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/forms.py
from django import forms
from .models import Product

class NewProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = [
			'name',
			'image',
			'price', 
			'discount_price',
			'quantity',
			'description',
		]

Products/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

"""
Product Dashboard
"""
@login_required
def productdashboard(request):
	all_products = Product.objects.all()
	all_category = Category.objects.all()
	empty_products_list = []
	count = 0
	for each in all_category:

		each_product = Product.objects.filter(productcategory__category = each)
		empty_list = []
		for each1 in each_product:
			empty_list.append(each1)
		empty_products_list.append({
			each.id:empty_list
		})

	return render(request, 'admin/products/eco-products.html',{"all_products":all_products,'all_category':all_category,"products_list":empty_products_list})

@login_required
def addproductdashboard(request):

	all_category = Category.objects.all()
	all_size = Size.objects.all()
	all_material = Material.objects.all()
	all_color = Color.objects.all()
	all_design = Design.objects.all()
	context = {
		'all_category':all_category,
		'all_size':all_size,
		'all_material':all_material,
		'all_color':all_color,
		'all_design':all_design,
		}
	if request.method=='POST':

		if Product.objects.filter(name=request.POST.get('name', None)):
			messages.error(request, 'product name is already exists.')
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

		if not request.POST.get('name'):
			messages.error(request, 'Please enter name.')
			return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

		if not request.FILES.get('image'):
			messages.error(request, 'Please enter image.')
			return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

		if not request.POST.get('category'):
			messages.error(request, 'Please enter category.')
			return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

		category_obj = Category.objects.filter(name = request.POST.get('category', None)).first()

		new_product_obj =  Product.objects.create(
			name =  request.POST.get('name'),
			slug =  request.POST.get('name'),
			# image =  request.FILES.get('image'),
			price =  request.POST.get('price'),
			description =  request.POST.get('description'),
			quantity =  request.POST.get('quantity'),
			discount_price =  request.POST.get('discount_price'),
		)

		if request.FILES.getlist('image') and new_product_obj:
			images = request.FILES.getlist('image')
			if images:
				new_product_obj.image = images[0]
				new_product_obj.save()
				for each in images:
					product_image_obj = ProductImages.objects.create(
						product = new_product_obj,
						image = each
					)
		quantity = 0
		if request.POST.get('quantity'):
			quantity = request.POST.get('quantity')

		add__to_category = ProductCategory.objects.create(
				product = new_product_obj,
				category = category_obj,
				quantity = quantity,
				status = True,
		)
		add_to_product_rating = ProductRating.objects.create(
				product = new_product_obj,
				rating_star = 0
		)

		for each in all_design:
			if each.name in request.POST:

				design_obj = Design.objects.filter(name = each.name)
				if design_obj :
					add_to_design = ProductDesign.objects.create(
						product =  new_product_obj,
						design = design_obj.first(),
						quantity = quantity,
						status = True
					)

		for each in all_size:
			if each.name in request.POST:

				size_obj = Size.objects.filter(name = each.name)
				if size_obj :
					add_to_size = ProductSize.objects.create(
						product =  new_product_obj,
						size = size_obj.first(),
						quantity = quantity,
						status = True
					)

		for each in all_material:
			if each.name in request.POST:

				material_obj = Material.objects.filter(name = each.name)
				if material_obj :
					add_to_material = ProductMaterial.objects.create(
						product =  new_product_obj,
						material = material_obj.first(),
						quantity = quantity,
						status = True
					)

		for each in all_color:
			if each.name in request.POST:

				color_obj = Color.objects.filter(name = each.name)
				if color_obj :
					add_to_color = ProductColor.objects.create(
						product =  new_product_obj,
						color = color_obj.first(),
						quantity = quantity,
						status = True
					)

		if add__to_category:
			messages.error(request, 'Product Added Succesfully.')
			return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


	return render(request, 'admin/products/eco-product-add.html',context)

@login_required
def editproductdashboard(request,pk):

	product_obj = Product.objects.get(pk=pk)
	all_category = Category.objects.all()
	all_size = Size.objects.all()
	all_material = Material.objects.all()
	all_color = Color.objects.all()
	all_design = Design.objects.all()

	product_size = ProductSize.objects.filter(product = product_obj)
	product_material = ProductMaterial.objects.filter(product = product_obj)
	product_color = ProductColor.objects.filter(product = product_obj)
	product_design = ProductDesign.objects.filter(product = product_obj)

	context = {
		'product':product_obj,
		'all_category':all_category,
		'all_size':all_size,
		'all_material':all_material,
		'all_color':all_color,
		'all_design':all_design,
		'product_size':product_size,
		'product_material':product_material,
		'product_color':product_color,
		'product_design':product_design,
	}

	if request.method=='POST' and product_obj:

		category_obj = Category.objects.filter(name = request.POST.get('category', None)).first()
		quantity = 0
		if request.POST.get('quantity'):
			quantity = int(request.POST.get('quantity'))

		if category_obj:
			try:
				add__to_category = ProductCategory.objects.get(
					product = product_obj,
					status = True
				)

				add__to_category.category = category_obj
				add__to_category.quantity = quantity
				add__to_category.save()
			except :

				add__to_category = ProductCategory.objects.create(
					product = product_obj,
					category = category_obj,
					quantity = quantity,
					status = True
				)
		else:
			messages.error(request, 'category is invalid.')
			return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
		if request.POST.get('name'):
			product_obj.name = request.POST.get('name')

		if request.FILES.getlist('image'):
			images = request.FILES.getlist('image')
			if images:
				product_obj.image = images[0]
				product_obj.save()
				all_product_images = ProductImages.objects.filter(product = product_obj)
				all_product_images.delete()
				for each in images:
					product_image_obj = ProductImages.objects.create(
						product = product_obj,
						image = each
					)

		if request.POST.get('price'):
			product_obj.price = request.POST.get('price')

		if request.POST.get('discount_price'):
			product_obj.discount_price = request.POST.get('discount_price')

		if request.POST.get('additional_information'):
			product_obj.additional_information = request.POST.get('additional_information')

		if request.POST.get('quantity'):
			product_obj.quantity = quantity

		if request.POST.get('description'):
			product_obj.description = request.POST.get('description')

		product_material_all = ProductMaterial.objects.filter(product =  product_obj)
		product_material_all.delete()

		product_design_all = ProductDesign.objects.filter(product =  product_obj)
		product_design_all.delete()

		product_size_all = ProductSize.objects.filter(product =  product_obj)
		product_size_all.delete()

		product_color_all = ProductColor.objects.filter(product =  product_obj)
		product_color_all.delete()

		for each in all_design:
			if each.name in request.POST:

				design_obj = Design.objects.filter(name = each.name)
				if design_obj :
					add_to_design = ProductDesign.objects.create(
						product =  product_obj,
						design = design_obj.first(),
						quantity = quantity,
						status = True
					)

		for each in all_size:
			if each.name in request.POST:

				size_obj = Size.objects.filter(name = each.name)
				if size_obj :
					add_to_size = ProductSize.objects.create(
						product =  product_obj,
						size = size_obj.first(),
						quantity = quantity,
						status = True
					)

		for each in all_material:
			if each.name in request.POST:

				material_obj = Material.objects.filter(name = each.name)

				if material_obj :
					add_to_material = ProductMaterial.objects.create(
						product =  product_obj,
						material = material_obj.first(),
						quantity = quantity,
						status = True
					)

		for each in all_color:
			if each.name in request.POST:
				color_obj = Color.objects.filter(name = each.name)
				if color_obj :
					add_to_color = ProductColor.objects.create(
						product =  product_obj,
						color = color_obj.first(),
						quantity = quantity,
						status = True
					)

		product_obj.save()
		return redirect('Products:product_dashboard')
	return render(request, 'admin/products/eco-product-edit.html',context)

@login_required
def deleteproductdashboard(request,pk):

	product_obj = Product.objects.get(pk=pk)
	if request.method=='POST' and product_obj:
		product_obj.delete()
		return redirect('Products:product_dashboard')
	return render(request, 'admin/products/eco-product-edit.html',{'product':product_obj})


"""
Category Dashboard
"""

@login_required
def category_dashboard(request):
	all_category = Category.objects.all()
	return render(request, 'admin/products/eco-category.html',{"all_category":all_category})


@login_required
def addcategorydashboard(request):

	if request.method=='POST':
		if Category.objects.filter(name=request.POST.get('name', None)):
			messages.error(request, 'category name is already exists.')
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

		if not request.POST.get('name'):
			messages.error(request, 'Please enter name.')
			return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

		new_category_obj =  Category.objects.create(
			name =  request.POST.get('name'),

templates/frontend/acessories.html
{% extends 'base.html' %}
  {% load static %}
    {% block content %}

      <div class="text-center top-div py-5">
        <div class="container">
          <h1>Accessories</h1>
          <p><a href="{% url 'frontend:index' %}">Home/</a><a href="{% url 'frontend:acessories' %}" style="color:black;">Accessories</a></p>
        </div>
      </div>
      <h1 class="by text-center mt-3">Shop by Categories</h1>
      <div class="mt-5">
          <div class="container">
              <div class="row justify-content-center">
                {% if category_obj %}
                  {% for each in  category_obj %}
                    <div class="card1  " style="width: 18rem;">
                      <div class="tsir">
                      <a href="{% url 'frontend:products' each.id %}"><img class="img-top pdd" src="{{ each.image.url }}" alt="Card image cap"></div></a>
                      <div class="card-body card-cus-12">
                        <a href="{% url 'frontend:products' each.id %}"  class="card-title cmt">{{ each.name  }}</a>
                      </div>
                    </div>
                  {% endfor %}
                {% endif %}
                    
              </div>
          </div>
      </div>
  {% endblock content %}

templates/frontend/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <section>
        <div class="text-center top-div py-5">
          <div class="container">
            <h1>Shopping Cart</h1>
            <p><a href="{% url 'frontend:index' %}">Home/</a><a href="{% url 'frontend:usercartlist' %}" style="color:black;">Cart</a></p>
          </div>
        </div>
        <section>
                <div class="container"> 
                    <div class="row cart-row mt-5">
                        <div class="col-md-12 col-lg-8 col-sm-12 col-xs-12 scrollable billing-list" id="cart_append_card">
                          <!-- <form action="{% url 'accounts:register' %}" id="sign_form" method="post"> -->
                          {% if request.user.is_authenticated %}  
                            {% if user_cartlist %}
                              {% for each in user_cartlist %}
                                
                                <div class="row border-cart ">
                                    <div class="col-md-4  col-lg-4 col-sm-6 col-xs-6  img-text-cart">
                                    <div class="small-jkt-img d-flex">
                                        <a href="singlepdct.html"><img src="{{ each.product.image.url }}" ></a>
                                        <h4>{{ each.product.name }}</h4> 
                                    </div>
                                </div>
                                    <!-- <div class="cart-dropdown"> -->
                                        <div class="col-md-4 col-lg-4 col-xs-6 col-sm-6 dropdown-cart d-flex">
                                        
                                          <p class="span-cart-552" >Size : <span>{{ each.size.name }}</span></p>
                                        </div>
                                    <!-- </div> -->
                                    <div class="col-md-2 col-lg-2 col-sm-6 col-xs-6 d-flex cart-qty">
                                        <div class="plus-minus-button">
                                            <form class="d-flex text-center">

                                                  <input type="number" id="number" class="number singlepdct_qunatity" disabled value="{{ each.qty }}" />
                                            </form>
                                          </div>
                                        </div>
                                          <div class="col-md-2 col-lg-2 col-sm-6 col-xs-6 cart-price">
                                              <div class="main-552 text-center">
                                              <p class="span-cart-552" >₹<span class="cart_price">{{ each.product.price }}</span></p>
                                            </div>
                                        </div>
                                        <span style="cursor: pointer;" onclick="remove_pro_from_cart('{{ each.product.name }}','{{ each.product.id }}')" ><i  class="fas fa-times cross-wrong"></i></span>
                                </div>
                              {% endfor %}
                            {% else %}
                            <h3>you cart is empty shop for add products</h3>
                            {% endif %}
                          {% else %}
                          <script>
                            update_cart_table()
                          </script>
                          {% endif %}
                          <!-- </form> -->
                        </div>
                        {% if user_cartlist %}
                          <div class="col-md-12 col-lg-4 col-xs-12 col-sm-12 cart-total-main">
                              <h4 class="text-center">Card Total</h4>
                              <hr>
                              <span class="cart-total">Sub Total</span><span class="cart-total-right" style="float:right;">₹<span id="total_before_shipping">0</span></span>
                              <br>
                              <hr>
                              <span class="cart-total">Shipping</span><span class="cart-total-right" style="float:right;">₹<span id="cart_shipping">0</span></span>
                              {% comment %} <br> {% endcomment %}
                              {% comment %} <span style="float:right;"><a href="shipping.html">Calculate Shipping</a></span> {% endcomment %}
                              {% comment %} <br> {% endcomment %}
                              <hr>
                              <span class="cart-total">Total</span><span class="cart-total-right" style="float:right;">₹<span id="total_after_shipping">0</span></span>
                              <br>
                              {% if request.user.is_authenticated %}
                                <a href="{% url 'frontend:usercheckout' %}"><button type="button">Checkout</button></a>
                              {% else %}
                              <a data-bs-toggle="modal" data-bs-target="#exampleModal"><button type="button">Checkout</button></a>
                              {% endif %}
                          </div>
                        {% endif %}
                        <div class="col-md-12 col-lg-8 col-xs-12 col-sm-12 cart-coupon mt-5">

                                <span class="coupon-right">
                                    <a href="{% url 'frontend:index' %}"><button type="submit">Continue Shopping</button> </a>
                                </span>
                            </ul>
                        </div>
                    </div>
                </div>
        </section>

        <script>
          function remove_pro_from_cart(product_name,product_id){
      
            /**
             * 
             */
    
            var response_status =  ajax_call_remove_cart(product_name,product_id)
            if (response_status){
              window.location.reload();
            } 
      }
        </script>
        <script>
          document.addEventListener("DOMContentLoaded", function(){
            var total_price = 0
            for(var i = 0; i < document.getElementsByClassName('cart_price').length; i++){
                var price = parseInt(document.getElementsByClassName('cart_price')[i].innerHTML)
                total_price = total_price + price
            }
            document.getElementById('total_before_shipping').innerHTML = total_price
            if (parseInt(total_price) >= 999){
              document.getElementById('cart_shipping').innerHTML = 0
            }else{
              document.getElementById('cart_shipping').innerHTML = 199
            }
            
            document.getElementById('total_after_shipping').innerHTML = parseInt(total_price) + parseInt(document.getElementById('cart_shipping').innerHTML)
          })
        </script>
    {% endblock content %}

templates/frontend/customize.html
{% extends 'base.html' %}
  {% load static %}
    {% block content %}
    <section>
        <div class="text-center top-div py-5">
            <div class="container">
                <h1>Customize Products</h1>
                <p><a href="{% url 'frontend:index' %}">Home/</a>
                    <a href="#">Categories/</a>
                    <a href="{% url 'frontend:usercustomeproduct' %}">Customize Products/</a>
                    <a href="#" style="color:black;">Men T-shirts</a>
                </p>
            </div>
        </div>
        <div class="container">
          <div class="spcl-offer">
            <img class="bimage-12 mt-3" src="{% static './images/summer sale.png' %}">
          </div>
        </div>
        <div class="container">
            <h1 class="custom mt-5">Custom Men T-Shirts <span>(3)</span> </h1>
            <div class="row mt-3">
                <div class="col-md-4 col-lg-4 col-sm-6 col-xs-6 mb-3">
                    <div class="card">
                       <div class="wishlist-card-icon">
                  <button class="product-slider__fav js-fav"><span class="heart"></span></button>
                </div>
                        <a href="{% url 'frontend:usercustomedesign' %}"><img src="{% static './images/Image.png' %}" class="card-img-top" alt="..."></a>
                        <div>
                            <span class="top-card-text">4 Color Options</span>
                            <span class="star-images" style="float:right;">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                            </span>
                        </div>
                        <hr>
                        <div>
                          <a href="{% url 'frontend:usercustomedesign' %}" class="card-text img-text">Customizable Black Printed T-shirt</a>
                        </div>
                        <div>
                            <p><span>₹107</span><span style="float:right;"><i class="fas fa-arrow-right"></i></span></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-4 col-sm-6 col-xs-6 mb-3">
                    <div class="card">
                       <div class="wishlist-card-icon">
                  <button class="product-slider__fav js-fav"><span class="heart"></span></button>
                </div>
                        <a href="{% url 'frontend:usercustomedesign' %}"><img src="{% static './images/red t shirt.png' %}" class="card-img-top" alt="..."></a>
                        <div>
                            <span class="top-card-text">5 Color Options</span>
                            <span class="star-images" style="float:right;">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                            </span>
                        </div>
                        <hr>
                        <div>
                          <a href="{% url 'frontend:usercustomedesign' %}" class="card-text img-text">Customizable Red Printed T-shirt</a>
                        </div>
                        <div>
                            <p><span>₹107</span><span style="float:right;"><i class="fas fa-arrow-right"></i></span></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-4 col-sm-6 col-xs-6 mb-3">
                    <div class="card">
                       <div class="wishlist-card-icon">
                  <button class="product-slider__fav js-fav"><span class="heart"></span></button>
                </div>
                       <a href="{% url 'frontend:usercustomedesign' %}"><img src="{% static './images/white t shirt.png' %}" class="card-img-top" alt="..."></a>
                        <div>
                            <span class="top-card-text">2 Color Options</span>
                            <span class="star-images" style="float:right;">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                            </span>
                        </div>
                        <hr>
                        <div>
                          <a href="{% url 'frontend:usercustomedesign' %}" class="card-text img-text">Customizable White Printed T-shirt</a>
                        </div>
                        <div>
                            <p><span>₹832</span><span style="float:right;"><i class="fas fa-arrow-right"></i></span></p>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </section>
  {% endblock content %}